#ifndef IREC_READER_H
#define IREC_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

typedef struct IREC_Interface IREC_Interface_t;
typedef const IREC_Interface_t *IREC_Interface_struct_t;
typedef IREC_Interface_t *IREC_Interface_mutable_struct_t;
typedef const IREC_Interface_t *IREC_Interface_vec_t;
typedef IREC_Interface_t *IREC_Interface_mutable_vec_t;
typedef struct IREC_MapEntryUlongUint IREC_MapEntryUlongUint_t;
typedef const IREC_MapEntryUlongUint_t *IREC_MapEntryUlongUint_struct_t;
typedef IREC_MapEntryUlongUint_t *IREC_MapEntryUlongUint_mutable_struct_t;
typedef const IREC_MapEntryUlongUint_t *IREC_MapEntryUlongUint_vec_t;
typedef IREC_MapEntryUlongUint_t *IREC_MapEntryUlongUint_mutable_vec_t;
typedef struct IREC_MapEntryUlongUlong IREC_MapEntryUlongUlong_t;
typedef const IREC_MapEntryUlongUlong_t *IREC_MapEntryUlongUlong_struct_t;
typedef IREC_MapEntryUlongUlong_t *IREC_MapEntryUlongUlong_mutable_struct_t;
typedef const IREC_MapEntryUlongUlong_t *IREC_MapEntryUlongUlong_vec_t;
typedef IREC_MapEntryUlongUlong_t *IREC_MapEntryUlongUlong_mutable_vec_t;
typedef struct IREC_HiddenPathExt IREC_HiddenPathExt_t;
typedef const IREC_HiddenPathExt_t *IREC_HiddenPathExt_struct_t;
typedef IREC_HiddenPathExt_t *IREC_HiddenPathExt_mutable_struct_t;
typedef const IREC_HiddenPathExt_t *IREC_HiddenPathExt_vec_t;
typedef IREC_HiddenPathExt_t *IREC_HiddenPathExt_mutable_vec_t;
typedef struct IREC_IrecExt IREC_IrecExt_t;
typedef const IREC_IrecExt_t *IREC_IrecExt_struct_t;
typedef IREC_IrecExt_t *IREC_IrecExt_mutable_struct_t;
typedef const IREC_IrecExt_t *IREC_IrecExt_vec_t;
typedef IREC_IrecExt_t *IREC_IrecExt_mutable_vec_t;
typedef struct IREC_HopField IREC_HopField_t;
typedef const IREC_HopField_t *IREC_HopField_struct_t;
typedef IREC_HopField_t *IREC_HopField_mutable_struct_t;
typedef const IREC_HopField_t *IREC_HopField_vec_t;
typedef IREC_HopField_t *IREC_HopField_mutable_vec_t;
typedef struct IREC_PeerEntry IREC_PeerEntry_t;
typedef const IREC_PeerEntry_t *IREC_PeerEntry_struct_t;
typedef IREC_PeerEntry_t *IREC_PeerEntry_mutable_struct_t;
typedef const IREC_PeerEntry_t *IREC_PeerEntry_vec_t;
typedef IREC_PeerEntry_t *IREC_PeerEntry_mutable_vec_t;

typedef const struct IREC_LatencyInfo_table *IREC_LatencyInfo_table_t;
typedef struct IREC_LatencyInfo_table *IREC_LatencyInfo_mutable_table_t;
typedef const flatbuffers_uoffset_t *IREC_LatencyInfo_vec_t;
typedef flatbuffers_uoffset_t *IREC_LatencyInfo_mutable_vec_t;
typedef const struct IREC_BandwidthInfo_table *IREC_BandwidthInfo_table_t;
typedef struct IREC_BandwidthInfo_table *IREC_BandwidthInfo_mutable_table_t;
typedef const flatbuffers_uoffset_t *IREC_BandwidthInfo_vec_t;
typedef flatbuffers_uoffset_t *IREC_BandwidthInfo_mutable_vec_t;
typedef const struct IREC_GeoCoordinates_table *IREC_GeoCoordinates_table_t;
typedef struct IREC_GeoCoordinates_table *IREC_GeoCoordinates_mutable_table_t;
typedef const flatbuffers_uoffset_t *IREC_GeoCoordinates_vec_t;
typedef flatbuffers_uoffset_t *IREC_GeoCoordinates_mutable_vec_t;
typedef const struct IREC_StaticInfoExt_table *IREC_StaticInfoExt_table_t;
typedef struct IREC_StaticInfoExt_table *IREC_StaticInfoExt_mutable_table_t;
typedef const flatbuffers_uoffset_t *IREC_StaticInfoExt_vec_t;
typedef flatbuffers_uoffset_t *IREC_StaticInfoExt_mutable_vec_t;
typedef const struct IREC_SignedExtensions_table *IREC_SignedExtensions_table_t;
typedef struct IREC_SignedExtensions_table *IREC_SignedExtensions_mutable_table_t;
typedef const flatbuffers_uoffset_t *IREC_SignedExtensions_vec_t;
typedef flatbuffers_uoffset_t *IREC_SignedExtensions_mutable_vec_t;
typedef const struct IREC_UnsignedExtensions_table *IREC_UnsignedExtensions_table_t;
typedef struct IREC_UnsignedExtensions_table *IREC_UnsignedExtensions_mutable_table_t;
typedef const flatbuffers_uoffset_t *IREC_UnsignedExtensions_vec_t;
typedef flatbuffers_uoffset_t *IREC_UnsignedExtensions_mutable_vec_t;
typedef const struct IREC_ASEntry_table *IREC_ASEntry_table_t;
typedef struct IREC_ASEntry_table *IREC_ASEntry_mutable_table_t;
typedef const flatbuffers_uoffset_t *IREC_ASEntry_vec_t;
typedef flatbuffers_uoffset_t *IREC_ASEntry_mutable_vec_t;
typedef const struct IREC_Beacon_table *IREC_Beacon_table_t;
typedef struct IREC_Beacon_table *IREC_Beacon_mutable_table_t;
typedef const flatbuffers_uoffset_t *IREC_Beacon_vec_t;
typedef flatbuffers_uoffset_t *IREC_Beacon_mutable_vec_t;
typedef const struct IREC_Execution_table *IREC_Execution_table_t;
typedef struct IREC_Execution_table *IREC_Execution_mutable_table_t;
typedef const flatbuffers_uoffset_t *IREC_Execution_vec_t;
typedef flatbuffers_uoffset_t *IREC_Execution_mutable_vec_t;
#ifndef IREC_Interface_file_identifier
#define IREC_Interface_file_identifier 0
#endif
/* deprecated, use IREC_Interface_file_identifier */
#ifndef IREC_Interface_identifier
#define IREC_Interface_identifier 0
#endif
#define IREC_Interface_type_hash ((flatbuffers_thash_t)0x10b1e527)
#define IREC_Interface_type_identifier "\x27\xe5\xb1\x10"
#ifndef IREC_Interface_file_extension
#define IREC_Interface_file_extension "bin"
#endif
#ifndef IREC_MapEntryUlongUint_file_identifier
#define IREC_MapEntryUlongUint_file_identifier 0
#endif
/* deprecated, use IREC_MapEntryUlongUint_file_identifier */
#ifndef IREC_MapEntryUlongUint_identifier
#define IREC_MapEntryUlongUint_identifier 0
#endif
#define IREC_MapEntryUlongUint_type_hash ((flatbuffers_thash_t)0xf9bbbc0b)
#define IREC_MapEntryUlongUint_type_identifier "\x0b\xbc\xbb\xf9"
#ifndef IREC_MapEntryUlongUint_file_extension
#define IREC_MapEntryUlongUint_file_extension "bin"
#endif
#ifndef IREC_MapEntryUlongUlong_file_identifier
#define IREC_MapEntryUlongUlong_file_identifier 0
#endif
/* deprecated, use IREC_MapEntryUlongUlong_file_identifier */
#ifndef IREC_MapEntryUlongUlong_identifier
#define IREC_MapEntryUlongUlong_identifier 0
#endif
#define IREC_MapEntryUlongUlong_type_hash ((flatbuffers_thash_t)0x7db27e1c)
#define IREC_MapEntryUlongUlong_type_identifier "\x1c\x7e\xb2\x7d"
#ifndef IREC_MapEntryUlongUlong_file_extension
#define IREC_MapEntryUlongUlong_file_extension "bin"
#endif
#ifndef IREC_LatencyInfo_file_identifier
#define IREC_LatencyInfo_file_identifier 0
#endif
/* deprecated, use IREC_LatencyInfo_file_identifier */
#ifndef IREC_LatencyInfo_identifier
#define IREC_LatencyInfo_identifier 0
#endif
#define IREC_LatencyInfo_type_hash ((flatbuffers_thash_t)0x73997fde)
#define IREC_LatencyInfo_type_identifier "\xde\x7f\x99\x73"
#ifndef IREC_LatencyInfo_file_extension
#define IREC_LatencyInfo_file_extension "bin"
#endif
#ifndef IREC_BandwidthInfo_file_identifier
#define IREC_BandwidthInfo_file_identifier 0
#endif
/* deprecated, use IREC_BandwidthInfo_file_identifier */
#ifndef IREC_BandwidthInfo_identifier
#define IREC_BandwidthInfo_identifier 0
#endif
#define IREC_BandwidthInfo_type_hash ((flatbuffers_thash_t)0xa99f1315)
#define IREC_BandwidthInfo_type_identifier "\x15\x13\x9f\xa9"
#ifndef IREC_BandwidthInfo_file_extension
#define IREC_BandwidthInfo_file_extension "bin"
#endif
#ifndef IREC_GeoCoordinates_file_identifier
#define IREC_GeoCoordinates_file_identifier 0
#endif
/* deprecated, use IREC_GeoCoordinates_file_identifier */
#ifndef IREC_GeoCoordinates_identifier
#define IREC_GeoCoordinates_identifier 0
#endif
#define IREC_GeoCoordinates_type_hash ((flatbuffers_thash_t)0x3dde09dc)
#define IREC_GeoCoordinates_type_identifier "\xdc\x09\xde\x3d"
#ifndef IREC_GeoCoordinates_file_extension
#define IREC_GeoCoordinates_file_extension "bin"
#endif
#ifndef IREC_StaticInfoExt_file_identifier
#define IREC_StaticInfoExt_file_identifier 0
#endif
/* deprecated, use IREC_StaticInfoExt_file_identifier */
#ifndef IREC_StaticInfoExt_identifier
#define IREC_StaticInfoExt_identifier 0
#endif
#define IREC_StaticInfoExt_type_hash ((flatbuffers_thash_t)0xcb9fad19)
#define IREC_StaticInfoExt_type_identifier "\x19\xad\x9f\xcb"
#ifndef IREC_StaticInfoExt_file_extension
#define IREC_StaticInfoExt_file_extension "bin"
#endif
#ifndef IREC_HiddenPathExt_file_identifier
#define IREC_HiddenPathExt_file_identifier 0
#endif
/* deprecated, use IREC_HiddenPathExt_file_identifier */
#ifndef IREC_HiddenPathExt_identifier
#define IREC_HiddenPathExt_identifier 0
#endif
#define IREC_HiddenPathExt_type_hash ((flatbuffers_thash_t)0x3b187b32)
#define IREC_HiddenPathExt_type_identifier "\x32\x7b\x18\x3b"
#ifndef IREC_HiddenPathExt_file_extension
#define IREC_HiddenPathExt_file_extension "bin"
#endif
#ifndef IREC_IrecExt_file_identifier
#define IREC_IrecExt_file_identifier 0
#endif
/* deprecated, use IREC_IrecExt_file_identifier */
#ifndef IREC_IrecExt_identifier
#define IREC_IrecExt_identifier 0
#endif
#define IREC_IrecExt_type_hash ((flatbuffers_thash_t)0x8d32140a)
#define IREC_IrecExt_type_identifier "\x0a\x14\x32\x8d"
#ifndef IREC_IrecExt_file_extension
#define IREC_IrecExt_file_extension "bin"
#endif
#ifndef IREC_SignedExtensions_file_identifier
#define IREC_SignedExtensions_file_identifier 0
#endif
/* deprecated, use IREC_SignedExtensions_file_identifier */
#ifndef IREC_SignedExtensions_identifier
#define IREC_SignedExtensions_identifier 0
#endif
#define IREC_SignedExtensions_type_hash ((flatbuffers_thash_t)0x5e587b56)
#define IREC_SignedExtensions_type_identifier "\x56\x7b\x58\x5e"
#ifndef IREC_SignedExtensions_file_extension
#define IREC_SignedExtensions_file_extension "bin"
#endif
#ifndef IREC_UnsignedExtensions_file_identifier
#define IREC_UnsignedExtensions_file_identifier 0
#endif
/* deprecated, use IREC_UnsignedExtensions_file_identifier */
#ifndef IREC_UnsignedExtensions_identifier
#define IREC_UnsignedExtensions_identifier 0
#endif
#define IREC_UnsignedExtensions_type_hash ((flatbuffers_thash_t)0xbbc7d25)
#define IREC_UnsignedExtensions_type_identifier "\x25\x7d\xbc\x0b"
#ifndef IREC_UnsignedExtensions_file_extension
#define IREC_UnsignedExtensions_file_extension "bin"
#endif
#ifndef IREC_HopField_file_identifier
#define IREC_HopField_file_identifier 0
#endif
/* deprecated, use IREC_HopField_file_identifier */
#ifndef IREC_HopField_identifier
#define IREC_HopField_identifier 0
#endif
#define IREC_HopField_type_hash ((flatbuffers_thash_t)0x5b60415d)
#define IREC_HopField_type_identifier "\x5d\x41\x60\x5b"
#ifndef IREC_HopField_file_extension
#define IREC_HopField_file_extension "bin"
#endif
#ifndef IREC_PeerEntry_file_identifier
#define IREC_PeerEntry_file_identifier 0
#endif
/* deprecated, use IREC_PeerEntry_file_identifier */
#ifndef IREC_PeerEntry_identifier
#define IREC_PeerEntry_identifier 0
#endif
#define IREC_PeerEntry_type_hash ((flatbuffers_thash_t)0xf2b7f72c)
#define IREC_PeerEntry_type_identifier "\x2c\xf7\xb7\xf2"
#ifndef IREC_PeerEntry_file_extension
#define IREC_PeerEntry_file_extension "bin"
#endif
#ifndef IREC_ASEntry_file_identifier
#define IREC_ASEntry_file_identifier 0
#endif
/* deprecated, use IREC_ASEntry_file_identifier */
#ifndef IREC_ASEntry_identifier
#define IREC_ASEntry_identifier 0
#endif
#define IREC_ASEntry_type_hash ((flatbuffers_thash_t)0x99af5318)
#define IREC_ASEntry_type_identifier "\x18\x53\xaf\x99"
#ifndef IREC_ASEntry_file_extension
#define IREC_ASEntry_file_extension "bin"
#endif
#ifndef IREC_Beacon_file_identifier
#define IREC_Beacon_file_identifier 0
#endif
/* deprecated, use IREC_Beacon_file_identifier */
#ifndef IREC_Beacon_identifier
#define IREC_Beacon_identifier 0
#endif
#define IREC_Beacon_type_hash ((flatbuffers_thash_t)0xf960bf88)
#define IREC_Beacon_type_identifier "\x88\xbf\x60\xf9"
#ifndef IREC_Beacon_file_extension
#define IREC_Beacon_file_extension "bin"
#endif
#ifndef IREC_Execution_file_identifier
#define IREC_Execution_file_identifier 0
#endif
/* deprecated, use IREC_Execution_file_identifier */
#ifndef IREC_Execution_identifier
#define IREC_Execution_identifier 0
#endif
#define IREC_Execution_type_hash ((flatbuffers_thash_t)0x5d43d272)
#define IREC_Execution_type_identifier "\x72\xd2\x43\x5d"
#ifndef IREC_Execution_file_extension
#define IREC_Execution_file_extension "bin"
#endif


struct IREC_Interface {
    alignas(4) uint32_t id;
};
static_assert(sizeof(IREC_Interface_t) == 4, "struct size mismatch");

static inline const IREC_Interface_t *IREC_Interface__const_ptr_add(const IREC_Interface_t *p, size_t i) { return p + i; }
static inline IREC_Interface_t *IREC_Interface__ptr_add(IREC_Interface_t *p, size_t i) { return p + i; }
static inline IREC_Interface_struct_t IREC_Interface_vec_at(IREC_Interface_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t IREC_Interface__size(void) { return 4; }
static inline size_t IREC_Interface_vec_len(IREC_Interface_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(IREC_Interface)

__flatbuffers_define_struct_scalar_field(IREC_Interface, id, flatbuffers_uint32, uint32_t)

struct IREC_MapEntryUlongUint {
    alignas(8) uint64_t k;
    alignas(4) uint32_t v;
};
static_assert(sizeof(IREC_MapEntryUlongUint_t) == 16, "struct size mismatch");

static inline const IREC_MapEntryUlongUint_t *IREC_MapEntryUlongUint__const_ptr_add(const IREC_MapEntryUlongUint_t *p, size_t i) { return p + i; }
static inline IREC_MapEntryUlongUint_t *IREC_MapEntryUlongUint__ptr_add(IREC_MapEntryUlongUint_t *p, size_t i) { return p + i; }
static inline IREC_MapEntryUlongUint_struct_t IREC_MapEntryUlongUint_vec_at(IREC_MapEntryUlongUint_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t IREC_MapEntryUlongUint__size(void) { return 16; }
static inline size_t IREC_MapEntryUlongUint_vec_len(IREC_MapEntryUlongUint_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(IREC_MapEntryUlongUint)

__flatbuffers_define_struct_scalar_field(IREC_MapEntryUlongUint, k, flatbuffers_uint64, uint64_t)
__flatbuffers_define_struct_scalar_field(IREC_MapEntryUlongUint, v, flatbuffers_uint32, uint32_t)

struct IREC_MapEntryUlongUlong {
    alignas(8) uint64_t k;
    alignas(8) uint64_t v;
};
static_assert(sizeof(IREC_MapEntryUlongUlong_t) == 16, "struct size mismatch");

static inline const IREC_MapEntryUlongUlong_t *IREC_MapEntryUlongUlong__const_ptr_add(const IREC_MapEntryUlongUlong_t *p, size_t i) { return p + i; }
static inline IREC_MapEntryUlongUlong_t *IREC_MapEntryUlongUlong__ptr_add(IREC_MapEntryUlongUlong_t *p, size_t i) { return p + i; }
static inline IREC_MapEntryUlongUlong_struct_t IREC_MapEntryUlongUlong_vec_at(IREC_MapEntryUlongUlong_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t IREC_MapEntryUlongUlong__size(void) { return 16; }
static inline size_t IREC_MapEntryUlongUlong_vec_len(IREC_MapEntryUlongUlong_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(IREC_MapEntryUlongUlong)

__flatbuffers_define_struct_scalar_field(IREC_MapEntryUlongUlong, k, flatbuffers_uint64, uint64_t)
__flatbuffers_define_struct_scalar_field(IREC_MapEntryUlongUlong, v, flatbuffers_uint64, uint64_t)

struct IREC_HiddenPathExt {
    alignas(1) flatbuffers_bool_t is_hidden;
};
static_assert(sizeof(IREC_HiddenPathExt_t) == 1, "struct size mismatch");

static inline const IREC_HiddenPathExt_t *IREC_HiddenPathExt__const_ptr_add(const IREC_HiddenPathExt_t *p, size_t i) { return p + i; }
static inline IREC_HiddenPathExt_t *IREC_HiddenPathExt__ptr_add(IREC_HiddenPathExt_t *p, size_t i) { return p + i; }
static inline IREC_HiddenPathExt_struct_t IREC_HiddenPathExt_vec_at(IREC_HiddenPathExt_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t IREC_HiddenPathExt__size(void) { return 1; }
static inline size_t IREC_HiddenPathExt_vec_len(IREC_HiddenPathExt_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(IREC_HiddenPathExt)

__flatbuffers_define_struct_scalar_field(IREC_HiddenPathExt, is_hidden, flatbuffers_bool, flatbuffers_bool_t)

struct IREC_IrecExt {
    alignas(4) uint32_t intf_group;
};
static_assert(sizeof(IREC_IrecExt_t) == 4, "struct size mismatch");

static inline const IREC_IrecExt_t *IREC_IrecExt__const_ptr_add(const IREC_IrecExt_t *p, size_t i) { return p + i; }
static inline IREC_IrecExt_t *IREC_IrecExt__ptr_add(IREC_IrecExt_t *p, size_t i) { return p + i; }
static inline IREC_IrecExt_struct_t IREC_IrecExt_vec_at(IREC_IrecExt_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t IREC_IrecExt__size(void) { return 4; }
static inline size_t IREC_IrecExt_vec_len(IREC_IrecExt_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(IREC_IrecExt)

__flatbuffers_define_struct_scalar_field(IREC_IrecExt, intf_group, flatbuffers_uint32, uint32_t)

struct IREC_HopField {
    alignas(8) uint64_t ingress;
    alignas(8) uint64_t egress;
    alignas(4) uint32_t exp_time;
};
static_assert(sizeof(IREC_HopField_t) == 24, "struct size mismatch");

static inline const IREC_HopField_t *IREC_HopField__const_ptr_add(const IREC_HopField_t *p, size_t i) { return p + i; }
static inline IREC_HopField_t *IREC_HopField__ptr_add(IREC_HopField_t *p, size_t i) { return p + i; }
static inline IREC_HopField_struct_t IREC_HopField_vec_at(IREC_HopField_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t IREC_HopField__size(void) { return 24; }
static inline size_t IREC_HopField_vec_len(IREC_HopField_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(IREC_HopField)

__flatbuffers_define_struct_scalar_field(IREC_HopField, ingress, flatbuffers_uint64, uint64_t)
__flatbuffers_define_struct_scalar_field(IREC_HopField, egress, flatbuffers_uint64, uint64_t)
__flatbuffers_define_struct_scalar_field(IREC_HopField, exp_time, flatbuffers_uint32, uint32_t)

struct IREC_PeerEntry {
    alignas(8) uint64_t peer_isd_as;
    alignas(8) uint64_t peer_interface;
    alignas(4) uint32_t peer_mtu;
    alignas(8) IREC_HopField_t hop_field;
};
static_assert(sizeof(IREC_PeerEntry_t) == 48, "struct size mismatch");

static inline const IREC_PeerEntry_t *IREC_PeerEntry__const_ptr_add(const IREC_PeerEntry_t *p, size_t i) { return p + i; }
static inline IREC_PeerEntry_t *IREC_PeerEntry__ptr_add(IREC_PeerEntry_t *p, size_t i) { return p + i; }
static inline IREC_PeerEntry_struct_t IREC_PeerEntry_vec_at(IREC_PeerEntry_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t IREC_PeerEntry__size(void) { return 48; }
static inline size_t IREC_PeerEntry_vec_len(IREC_PeerEntry_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(IREC_PeerEntry)

__flatbuffers_define_struct_scalar_field(IREC_PeerEntry, peer_isd_as, flatbuffers_uint64, uint64_t)
__flatbuffers_define_struct_scalar_field(IREC_PeerEntry, peer_interface, flatbuffers_uint64, uint64_t)
__flatbuffers_define_struct_scalar_field(IREC_PeerEntry, peer_mtu, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_struct_field(IREC_PeerEntry, hop_field, IREC_HopField_struct_t)


struct IREC_LatencyInfo_table { uint8_t unused__; };

static inline size_t IREC_LatencyInfo_vec_len(IREC_LatencyInfo_vec_t vec)
__flatbuffers_vec_len(vec)
static inline IREC_LatencyInfo_table_t IREC_LatencyInfo_vec_at(IREC_LatencyInfo_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(IREC_LatencyInfo_table_t, vec, i, 0)
__flatbuffers_table_as_root(IREC_LatencyInfo)

__flatbuffers_define_vector_field(0, IREC_LatencyInfo, intra, IREC_MapEntryUlongUint_vec_t, 0)
__flatbuffers_define_vector_field(1, IREC_LatencyInfo, inter, IREC_MapEntryUlongUint_vec_t, 0)

struct IREC_BandwidthInfo_table { uint8_t unused__; };

static inline size_t IREC_BandwidthInfo_vec_len(IREC_BandwidthInfo_vec_t vec)
__flatbuffers_vec_len(vec)
static inline IREC_BandwidthInfo_table_t IREC_BandwidthInfo_vec_at(IREC_BandwidthInfo_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(IREC_BandwidthInfo_table_t, vec, i, 0)
__flatbuffers_table_as_root(IREC_BandwidthInfo)

__flatbuffers_define_vector_field(0, IREC_BandwidthInfo, intra, IREC_MapEntryUlongUlong_vec_t, 0)
__flatbuffers_define_vector_field(1, IREC_BandwidthInfo, inter, IREC_MapEntryUlongUlong_vec_t, 0)

struct IREC_GeoCoordinates_table { uint8_t unused__; };

static inline size_t IREC_GeoCoordinates_vec_len(IREC_GeoCoordinates_vec_t vec)
__flatbuffers_vec_len(vec)
static inline IREC_GeoCoordinates_table_t IREC_GeoCoordinates_vec_at(IREC_GeoCoordinates_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(IREC_GeoCoordinates_table_t, vec, i, 0)
__flatbuffers_table_as_root(IREC_GeoCoordinates)

__flatbuffers_define_scalar_field(0, IREC_GeoCoordinates, ifId, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, IREC_GeoCoordinates, latitude, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(2, IREC_GeoCoordinates, longitude, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_string_field(3, IREC_GeoCoordinates, address, 0)

struct IREC_StaticInfoExt_table { uint8_t unused__; };

static inline size_t IREC_StaticInfoExt_vec_len(IREC_StaticInfoExt_vec_t vec)
__flatbuffers_vec_len(vec)
static inline IREC_StaticInfoExt_table_t IREC_StaticInfoExt_vec_at(IREC_StaticInfoExt_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(IREC_StaticInfoExt_table_t, vec, i, 0)
__flatbuffers_table_as_root(IREC_StaticInfoExt)

__flatbuffers_define_table_field(0, IREC_StaticInfoExt, latency, IREC_LatencyInfo_table_t, 0)
__flatbuffers_define_table_field(1, IREC_StaticInfoExt, bandwidth, IREC_BandwidthInfo_table_t, 0)
__flatbuffers_define_vector_field(2, IREC_StaticInfoExt, geo, IREC_GeoCoordinates_vec_t, 0)
__flatbuffers_define_vector_field(3, IREC_StaticInfoExt, link_type, IREC_MapEntryUlongUint_vec_t, 0)
__flatbuffers_define_vector_field(4, IREC_StaticInfoExt, internal_hops, IREC_MapEntryUlongUint_vec_t, 0)
__flatbuffers_define_string_field(5, IREC_StaticInfoExt, note, 0)

struct IREC_SignedExtensions_table { uint8_t unused__; };

static inline size_t IREC_SignedExtensions_vec_len(IREC_SignedExtensions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline IREC_SignedExtensions_table_t IREC_SignedExtensions_vec_at(IREC_SignedExtensions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(IREC_SignedExtensions_table_t, vec, i, 0)
__flatbuffers_table_as_root(IREC_SignedExtensions)

__flatbuffers_define_table_field(0, IREC_SignedExtensions, static_info, IREC_StaticInfoExt_table_t, 0)
__flatbuffers_define_struct_field(1, IREC_SignedExtensions, hidden_path, IREC_HiddenPathExt_struct_t, 0)
__flatbuffers_define_struct_field(2, IREC_SignedExtensions, irec, IREC_IrecExt_struct_t, 0)

struct IREC_UnsignedExtensions_table { uint8_t unused__; };

static inline size_t IREC_UnsignedExtensions_vec_len(IREC_UnsignedExtensions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline IREC_UnsignedExtensions_table_t IREC_UnsignedExtensions_vec_at(IREC_UnsignedExtensions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(IREC_UnsignedExtensions_table_t, vec, i, 0)
__flatbuffers_table_as_root(IREC_UnsignedExtensions)


struct IREC_ASEntry_table { uint8_t unused__; };

static inline size_t IREC_ASEntry_vec_len(IREC_ASEntry_vec_t vec)
__flatbuffers_vec_len(vec)
static inline IREC_ASEntry_table_t IREC_ASEntry_vec_at(IREC_ASEntry_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(IREC_ASEntry_table_t, vec, i, 0)
__flatbuffers_table_as_root(IREC_ASEntry)

__flatbuffers_define_scalar_field(0, IREC_ASEntry, isd_as, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, IREC_ASEntry, next_isd_as, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(2, IREC_ASEntry, he_ingress_mtu, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_struct_field(3, IREC_ASEntry, hop_field, IREC_HopField_struct_t, 0)
__flatbuffers_define_vector_field(4, IREC_ASEntry, peer_entries, IREC_PeerEntry_vec_t, 0)
__flatbuffers_define_scalar_field(5, IREC_ASEntry, mtu, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_table_field(6, IREC_ASEntry, extensions, IREC_SignedExtensions_table_t, 0)
__flatbuffers_define_table_field(7, IREC_ASEntry, unsigned_extensions, IREC_UnsignedExtensions_table_t, 0)

struct IREC_Beacon_table { uint8_t unused__; };

static inline size_t IREC_Beacon_vec_len(IREC_Beacon_vec_t vec)
__flatbuffers_vec_len(vec)
static inline IREC_Beacon_table_t IREC_Beacon_vec_at(IREC_Beacon_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(IREC_Beacon_table_t, vec, i, 0)
__flatbuffers_table_as_root(IREC_Beacon)

__flatbuffers_define_vector_field(0, IREC_Beacon, segment_info, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_vector_field(1, IREC_Beacon, as_entries, IREC_ASEntry_vec_t, 0)
__flatbuffers_define_scalar_field(2, IREC_Beacon, inIfId, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(3, IREC_Beacon, id, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct IREC_Execution_table { uint8_t unused__; };

static inline size_t IREC_Execution_vec_len(IREC_Execution_vec_t vec)
__flatbuffers_vec_len(vec)
static inline IREC_Execution_table_t IREC_Execution_vec_at(IREC_Execution_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(IREC_Execution_table_t, vec, i, 0)
__flatbuffers_table_as_root(IREC_Execution)

__flatbuffers_define_vector_field(0, IREC_Execution, beacons, IREC_Beacon_vec_t, 0)
__flatbuffers_define_vector_field(1, IREC_Execution, algHash, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_vector_field(2, IREC_Execution, intfs, IREC_Interface_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* IREC_READER_H */
