// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package IREC

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BeaconBytesWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsBeaconBytesWrapper(buf []byte, offset flatbuffers.UOffsetT) *BeaconBytesWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BeaconBytesWrapper{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BeaconBytesWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BeaconBytesWrapper) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BeaconBytesWrapper) B(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BeaconBytesWrapper) BLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BeaconBytesWrapper) BBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BeaconBytesWrapper) MutateB(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func BeaconBytesWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BeaconBytesWrapperAddB(builder *flatbuffers.Builder, b flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(b), 0)
}
func BeaconBytesWrapperStartBVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BeaconBytesWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
