// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package IREC

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Interface struct {
	_tab flatbuffers.Struct
}

func (rcv *Interface) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Interface) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Interface) Id() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Interface) MutateId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateInterface(builder *flatbuffers.Builder, id uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 4)
	builder.PrependUint32(id)
	return builder.Offset()
}
