// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package IREC

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IrecExt struct {
	_tab flatbuffers.Struct
}

func (rcv *IrecExt) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IrecExt) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *IrecExt) IntfGroup() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *IrecExt) MutateIntfGroup(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateIrecExt(builder *flatbuffers.Builder, intfGroup uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 4)
	builder.PrependUint32(intfGroup)
	return builder.Offset()
}
