// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package IREC

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MapEntryUlongUint struct {
	_tab flatbuffers.Struct
}

func (rcv *MapEntryUlongUint) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MapEntryUlongUint) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *MapEntryUlongUint) K() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *MapEntryUlongUint) MutateK(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *MapEntryUlongUint) V() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *MapEntryUlongUint) MutateV(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateMapEntryUlongUint(builder *flatbuffers.Builder, k uint64, v uint32) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.Pad(4)
	builder.PrependUint32(v)
	builder.PrependUint64(k)
	return builder.Offset()
}
