// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package IREC

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MapEntryUlongUlong struct {
	_tab flatbuffers.Struct
}

func (rcv *MapEntryUlongUlong) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MapEntryUlongUlong) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *MapEntryUlongUlong) K() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *MapEntryUlongUlong) MutateK(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *MapEntryUlongUlong) V() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *MapEntryUlongUlong) MutateV(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateMapEntryUlongUlong(builder *flatbuffers.Builder, k uint64, v uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependUint64(v)
	builder.PrependUint64(k)
	return builder.Offset()
}
